//
//  capitals.swift
//  iPhone X Layout
//
//  Created by Yariv on 11/15/17.
//  Copyright © 2017 SwiftCoders. All rights reserved.
//

import Foundation

// Source: https://github.com/icyrockcom/country-capitals/blob/master/data/country-list.json

struct Capital {
    let country: String
    let city: String
}

final class DataSource {
    static let capitals =
        [
            Capital(country: "Abkhazia", city: "Sukhumi"),
            Capital(country: "Afghanistan", city: "Kabul"),
            Capital(country: "Akrotiri and Dhekelia", city: "Episkopi Cantonment"),
            Capital(country: "Albania", city: "Tirana"),
            Capital(country: "Algeria", city: "Algiers"),
            Capital(country: "American Samoa", city: "Pago Pago"),
            Capital(country: "Andorra", city: "Andorra la Vella"),
            Capital(country: "Angola", city: "Luanda"),
            Capital(country: "Anguilla", city: "The Valley"),
            Capital(country: "Antigua and Barbuda", city: "St. John's"),
            Capital(country: "Argentina", city: "Buenos Aires"),
            Capital(country: "Armenia", city: "Yerevan"),
            Capital(country: "Aruba", city: "Oranjestad"),
            Capital(country: "Ascension Island", city: "Georgetown"),
            Capital(country: "Australia", city: "Canberra"),
            Capital(country: "Austria", city: "Vienna"),
            Capital(country: "Azerbaijan", city: "Baku"),
            Capital(country: "Bahamas", city: "Nassau"),
            Capital(country: "Bahrain", city: "Manama"),
            Capital(country: "Bangladesh", city: "Dhaka"),
            Capital(country: "Barbados", city: "Bridgetown"),
            Capital(country: "Belarus", city: "Minsk"),
            Capital(country: "Belgium", city: "Brussels"),
            Capital(country: "Belize", city: "Belmopan"),
            Capital(country: "Benin", city: "Porto-Novo"),
            Capital(country: "Bermuda", city: "Hamilton"),
            Capital(country: "Bhutan", city: "Thimphu"),
            Capital(country: "Bolivia", city: "Sucre"),
            Capital(country: "Bolivia", city: "La Paz"),
            Capital(country: "Bosnia and Herzegovina", city: "Sarajevo"),
            Capital(country: "Botswana", city: "Gaborone"),
            Capital(country: "Brazil", city: "Brasília"),
            Capital(country: "British Virgin Islands", city: "Road Town"),
            Capital(country: "Brunei", city: "Bandar Seri Begawan"),
            Capital(country: "Bulgaria", city: "Sofia"),
            Capital(country: "Burkina Faso", city: "Ouagadougou"),
            Capital(country: "Burundi", city: "Bujumbura"),
            Capital(country: "Cambodia", city: "Phnom Penh"),
            Capital(country: "Cameroon", city: "Yaoundé"),
            Capital(country: "Canada", city: "Ottawa"),
            Capital(country: "Cape Verde", city: "Praia"),
            Capital(country: "Cayman Islands", city: "George Town"),
            Capital(country: "Central African Republic", city: "Bangui"),
            Capital(country: "Chad", city: "N'Djamena"),
            Capital(country: "Chile", city: "Santiago"),
            Capital(country: "China", city: "Beijing"),
            Capital(country: "Christmas Island", city: "Flying Fish Cove"),
            Capital(country: "Cocos (Keeling) Islands", city: "West Island"),
            Capital(country: "Colombia", city: "Bogotá"),
            Capital(country: "Comoros", city: "Moroni"),
            Capital(country: "Cook Islands", city: "Avarua"),
            Capital(country: "Costa Rica", city: "San José"),
            Capital(country: "Croatia", city: "Zagreb"),
            Capital(country: "Cuba", city: "Havana"),
            Capital(country: "Curaçao", city: "Willemstad"),
            Capital(country: "Cyprus", city: "Nicosia"),
            Capital(country: "Czech Republic", city: "Prague"),
            Capital(country: "Côte d'Ivoire", city: "Yamoussoukro"),
            Capital(country: "Democratic Republic of the Congo", city: "Kinshasa"),
            Capital(country: "Denmark", city: "Copenhagen"),
            Capital(country: "Djibouti", city: "Djibouti"),
            Capital(country: "Dominica", city: "Roseau"),
            Capital(country: "Dominican Republic", city: "Santo Domingo"),
            Capital(country: "East Timor (Timor-Leste)", city: "Dili"),
            Capital(country: "Easter Island", city: "Hanga Roa"),
            Capital(country: "Ecuador", city: "Quito"),
            Capital(country: "Egypt", city: "Cairo"),
            Capital(country: "El Salvador", city: "San Salvador"),
            Capital(country: "Equatorial Guinea", city: "Malabo"),
            Capital(country: "Eritrea", city: "Asmara"),
            Capital(country: "Estonia", city: "Tallinn"),
            Capital(country: "Ethiopia", city: "Addis Ababa"),
            Capital(country: "Falkland Islands", city: "Stanley"),
            Capital(country: "Faroe Islands", city: "Tórshavn"),
            Capital(country: "Federated States of Micronesia", city: "Palikir"),
            Capital(country: "Fiji", city: "Suva"),
            Capital(country: "Finland", city: "Helsinki"),
            Capital(country: "France", city: "Paris"),
            Capital(country: "French Guiana", city: "Cayenne"),
            Capital(country: "French Polynesia", city: "Papeete"),
            Capital(country: "Gabon", city: "Libreville"),
            Capital(country: "Gambia", city: "Banjul"),
            Capital(country: "Georgia", city: "Tbilisi"),
            Capital(country: "Germany", city: "Berlin"),
            Capital(country: "Ghana", city: "Accra"),
            Capital(country: "Gibraltar", city: "Gibraltar"),
            Capital(country: "Greece", city: "Athens"),
            Capital(country: "Greenland", city: "Nuuk"),
            Capital(country: "Grenada", city: "St. George's"),
            Capital(country: "Guam", city: "Hagåtña"),
            Capital(country: "Guatemala", city: "Guatemala City"),
            Capital(country: "Guernsey", city: "St. Peter Port"),
            Capital(country: "Guinea", city: "Conakry"),
            Capital(country: "Guinea-Bissau", city: "Bissau"),
            Capital(country: "Guyana", city: "Georgetown"),
            Capital(country: "Haiti", city: "Port-au-Prince"),/*
            Capital(country: "Honduras", city: "Tegucigalpa"),
            Capital(country: "Hungary", city: "Budapest"),
            Capital(country: "Iceland", city: "Reykjavík"),
            Capital(country: "India", city: "New Delhi"),
            Capital(country: "Indonesia", city: "Jakarta"),
            Capital(country: "Iran", city: "Tehran"),
            Capital(country: "Iraq", city: "Baghdad"),
            Capital(country: "Ireland", city: "Dublin"),
            Capital(country: "Isle of Man", city: "Douglas"),
            Capital(country: "Israel", city: "Jerusalem"),
            Capital(country: "Italy", city: "Rome"),
            Capital(country: "Jamaica", city: "Kingston"),
            Capital(country: "Japan", city: "Tokyo"),
            Capital(country: "Jersey", city: "St. Helier"),
            Capital(country: "Jordan", city: "Amman"),
            Capital(country: "Kazakhstan", city: "Astana"),
            Capital(country: "Kenya", city: "Nairobi"),
            Capital(country: "Kiribati", city: "Tarawa"),
            Capital(country: "Kosovo", city: "Pristina"),
            Capital(country: "Kuwait", city: "Kuwait City"),
            Capital(country: "Kyrgyzstan", city: "Bishkek"),
            Capital(country: "Laos", city: "Vientiane"),
            Capital(country: "Latvia", city: "Riga"),
            Capital(country: "Lebanon", city: "Beirut"),
            Capital(country: "Lesotho", city: "Maseru"),
            Capital(country: "Liberia", city: "Monrovia"),
            Capital(country: "Libya", city: "Tripoli"),
            Capital(country: "Liechtenstein", city: "Vaduz"),
            Capital(country: "Lithuania", city: "Vilnius"),
            Capital(country: "Luxembourg", city: "Luxembourg"),
            Capital(country: "Macedonia", city: "Skopje"),
            Capital(country: "Madagascar", city: "Antananarivo"),
            Capital(country: "Malawi", city: "Lilongwe"),
            Capital(country: "Malaysia", city: "Kuala Lumpur"),
            Capital(country: "Maldives", city: "Malé"),
            Capital(country: "Mali", city: "Bamako"),
            Capital(country: "Malta", city: "Valletta"),
            Capital(country: "Marshall Islands", city: "Majuro"),
            Capital(country: "Mauritania", city: "Nouakchott"),
            Capital(country: "Mauritius", city: "Port Louis"),
            Capital(country: "Mexico", city: "Mexico City"),
            Capital(country: "Moldova", city: "Chisinau"),
            Capital(country: "Monaco", city: "Monaco"),
            Capital(country: "Mongolia", city: "Ulaanbaatar"),
            Capital(country: "Montenegro", city: "Podgorica"),
            Capital(country: "Montserrat", city: "Plymouth"),
            Capital(country: "Morocco", city: "Rabat"),
            Capital(country: "Mozambique", city: "Maputo"),
            Capital(country: "Myanmar", city: "Naypyidaw"),
            Capital(country: "Nagorno-Karabakh Republic", city: "Stepanakert"),
            Capital(country: "Namibia", city: "Windhoek"),
            Capital(country: "Nauru", city: "Yaren"),
            Capital(country: "Nepal", city: "Kathmandu"),
            Capital(country: "Netherlands", city: "Amsterdam"),
            Capital(country: "New Caledonia", city: "Nouméa"),
            Capital(country: "New Zealand", city: "Wellington"),
            Capital(country: "Nicaragua", city: "Managua"),
            Capital(country: "Niger", city: "Niamey"),
            Capital(country: "Nigeria", city: "Abuja"),
            Capital(country: "Niue", city: "Alofi"),
            Capital(country: "Norfolk Island", city: "Kingston"),
            Capital(country: "North Korea", city: "Pyongyang"),
            Capital(country: "Northern Cyprus", city: "Nicosia"),
            Capital(country: "United Kingdom Northern Ireland", city: "Belfast"),
            Capital(country: "Northern Mariana Islands", city: "Saipan"),
            Capital(country: "Norway", city: "Oslo"),
            Capital(country: "Oman", city: "Muscat"),
            Capital(country: "Pakistan", city: "Islamabad"),
            Capital(country: "Palau", city: "Ngerulmud"),
            Capital(country: "Palestine", city: "Jerusalem"),
            Capital(country: "Panama", city: "Panama City"),
            Capital(country: "Papua New Guinea", city: "Port Moresby"),
            Capital(country: "Paraguay", city: "Asunción"),
            Capital(country: "Peru", city: "Lima"),
            Capital(country: "Philippines", city: "Manila"),
            Capital(country: "Pitcairn Islands", city: "Adamstown"),
            Capital(country: "Poland", city: "Warsaw"),
            Capital(country: "Portugal", city: "Lisbon"),
            Capital(country: "Puerto Rico", city: "San Juan"),
            Capital(country: "Qatar", city: "Doha"),
            Capital(country: "Republic of China (Taiwan)", city: "Taipei"),
            Capital(country: "Republic of the Congo", city: "Brazzaville"),
            Capital(country: "Romania", city: "Bucharest"),
            Capital(country: "Russia", city: "Moscow"),
            Capital(country: "Rwanda", city: "Kigali"),
            Capital(country: "Saint Barthélemy", city: "Gustavia"),
            Capital(country: "Saint Helena", city: "Jamestown"),
            Capital(country: "Saint Kitts and Nevis", city: "Basseterre"),
            Capital(country: "Saint Lucia", city: "Castries"),
            Capital(country: "Saint Martin", city: "Marigot"),
            Capital(country: "Saint Pierre and Miquelon", city: "St. Pierre"),
            Capital(country: "Saint Vincent and the Grenadines", city: "Kingstown"),
            Capital(country: "Samoa", city: "Apia"),
            Capital(country: "San Marino", city: "San Marino"),
            Capital(country: "Saudi Arabia", city: "Riyadh"),
            Capital(country: "Scotland", city: "Edinburgh"),
            Capital(country: "Senegal", city: "Dakar"),
            Capital(country: "Serbia", city: "Belgrade"),
            Capital(country: "Seychelles", city: "Victoria"),
            Capital(country: "Sierra Leone", city: "Freetown"),
            Capital(country: "Singapore", city: "Singapore"),
            Capital(country: "Sint Maarten", city: "Philipsburg"),
            Capital(country: "Slovakia", city: "Bratislava"),
            Capital(country: "Slovenia", city: "Ljubljana"),
            Capital(country: "Solomon Islands", city: "Honiara"),
            Capital(country: "Somalia", city: "Mogadishu"),
            Capital(country: "Somaliland", city: "Hargeisa"),
            Capital(country: "South Africa", city: "Pretoria"),
            Capital(country: "South Georgia and the South Sandwich Islands", city: "Grytviken"),
            Capital(country: "South Korea", city: "Seoul"),
            Capital(country: "South Ossetia", city: "Tskhinvali"),
            Capital(country: "South Sudan South Sudan", city: "Juba"),
            Capital(country: "Spain", city: "Madrid"),
            Capital(country: "Sri Lanka", city: "Sri Jayawardenapura Kotte"),
            Capital(country: "Sudan", city: "Khartoum"),
            Capital(country: "Suriname", city: "Paramaribo"),
            Capital(country: "Swaziland", city: "Mbabane"),
            Capital(country: "Sweden", city: "Stockholm"),
            Capital(country: "Switzerland", city: "Bern"),
            Capital(country: "Syria", city: "Damascus"),
            Capital(country: "São Tomé and Príncipe", city: "São Tomé"),
            Capital(country: "Tajikistan", city: "Dushanbe"),
            Capital(country: "Tanzania", city: "Dodoma"),
            Capital(country: "Thailand", city: "Bangkok"),
            Capital(country: "Togo", city: "Lomé"),
            Capital(country: "Tonga", city: "Nukuʻalofa"),
            Capital(country: "Transnistria", city: "Tiraspol"),
            Capital(country: "Trinidad and Tobago", city: "Port of Spain"),
            Capital(country: "Tristan da Cunha", city: "Edinburgh of the Seven Seas"),
            Capital(country: "Tunisia", city: "Tunis"),
            Capital(country: "Turkey", city: "Ankara"),
            Capital(country: "Turkmenistan", city: "Ashgabat"),
            Capital(country: "Turks and Caicos Islands", city: "Cockburn Town"),
            Capital(country: "Tuvalu", city: "Funafuti"),
            Capital(country: "Uganda", city: "Kampala"),
            Capital(country: "Ukraine", city: "Kiev"),
            Capital(country: "United Arab Emirates", city: "Abu Dhabi"),
            Capital(country: "United Kingdom; England", city: "London"),
            Capital(country: "United States", city: "Washington, D.C."),
            Capital(country: "United States Virgin Islands", city: "Charlotte Amalie"),
            Capital(country: "Uruguay", city: "Montevideo"),
            Capital(country: "Uzbekistan", city: "Tashkent"),
            Capital(country: "Vanuatu", city: "Port Vila"),
            Capital(country: "Vatican City", city: "Vatican City"),
            Capital(country: "Venezuela", city: "Caracas"),
            Capital(country: "Vietnam", city: "Hanoi"),
            Capital(country: "Wales", city: "Cardiff"),
            Capital(country: "Wallis and Futuna", city: "Mata-Utu"),
            Capital(country: "Western Sahara", city: "El Aaiún"),
            Capital(country: "Yemen", city: "Sanaá"),
            Capital(country: "Zambia", city: "Lusaka"),
            Capital(country: "Zimbabwe", city: "Harare")*/
    ]
}
